apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-server
  template:
    metadata:
      labels:
        app: socket-server
    spec:
      containers:
      - name: socket-server
        image: server-<your student ID>
        imagePullPolicy: Never
        ports:
        - containerPort: 8888